OcupacaoMaquinaOFC/Controllers/MaquinasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OcupacaoMaquinaOFC.Data;
using OcupacaoMaquinaOFC.Models;

namespace OcupacaoMaquinaOFC.Controllers
{
    public class MaquinasController : Controller
    {

        //List<Maquina> CriarListaEquipamentos()
        //{
        //    return SeedData.LISTADEQUIPAMENTOS;
        //}


        //void PopularBancoDeMaquinas()
        //{
        //    SeedData.equipamentos.AddRange(CriarListaEquipamentos());
        //}

        //void CriarNovaMaquina(string nome, double limiteHoras, double valorMaquina)
        //{
        //    SeedData.equipamentos.Add(new Maquina(nome, limiteHoras, valorMaquina));
        //}

        //void CriarNovaMaquinaComInput()
        //{
        //    Console.WriteLine("\nInsira os dados para cadastrar uma máquina abaixo:");
        //    Console.Write("Nome: ");
        //    string nome = Console.ReadLine();
        //    Console.Write("Limite de horas da máquina: ");
        //    double limiteHoras = Convert.ToDouble(Console.ReadLine());
        //    Console.Write("Valor da máquina: ");
        //    double valorMaquina = Convert.ToDouble(Console.ReadLine());
        //    CriarNovaMaquina(nome, limiteHoras, valorMaquina);

        //}
        //    void ExibirEquipamentos()
        //    {
        //        foreach (var equipamento in SeedData.equipamentos)
        //        {
        //            Console.WriteLine(equipamento.nome);
        //        }
        //    }
        //}
        public void calcularValorHora(Maquina maquina)
        {
            maquina.ValorHora = ((maquina.ValorMaquina * 0.10) / 365) / 24;
        }

        private readonly OcupacaoMaquinaOFCContext _context;

        public MaquinasController(OcupacaoMaquinaOFCContext context)
        {
            _context = context;
        }

        // GET: Maquinas
        public async Task<IActionResult> Index(string searchString)
        {
            if (_context.Maquina == null)
            {
                return Problem("Entity set 'OcupacaoMaquinaOFCContext.Maquina'  is null.");
            }

            var maquinas = from m in _context.Maquina
                           select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                maquinas = maquinas.Where(s => s.Nome!.Contains(searchString));
            }

            return View(await maquinas.ToListAsync());

        }

        // GET: Maquinas/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (_context.Maquina == null)
            {
                return NotFound();
            }

            var maquina = await _context.Maquina
                .FirstOrDefaultAsync(m => m.Id == id);
            if (maquina == null)
            {
                return NotFound();
            }

            return View(maquina);
        }

        // GET: Maquinas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Maquinas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("nome,limiteHoras,valorMaquina")] Maquina maquina)
        {
            if (ModelState.IsValid)
            {
                calcularValorHora(maquina);

                _context.Add(maquina);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(maquina);
            }
        }

        // GET: Maquinas/Edit/5
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if (_context.Maquina == null)
            {
                return NotFound();
            }

            var maquina = await _context.Maquina.FindAsync(id);

            if (maquina == null)
            {
                return NotFound();
            }

            return View(maquina);
        }

        // POST: Maquinas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id, nome,limiteHoras,valorMaquina,valorHora")] Maquina maquina)
        {
            if (id != maquina.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(maquina);
                    calcularValorHora(maquina);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MaquinaExists(maquina.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(maquina);
        }

        // GET: Maquinas/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (_context.Maquina == null)
            {
                return NotFound();
            }

            var maquina = await _context.Maquina
                .FirstOrDefaultAsync(m => m.Id == id);
            if (maquina == null)
            {
                return NotFound();
            }

            return View(maquina);
        }

        // POST: Maquinas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Maquina == null)
            {
                return Problem("Entity set 'OcupacaoMaquinaOFCContext.Maquina'  is null.");
            }
            var maquina = await _context.Maquina.FindAsync(id);
            if (maquina != null)
            {
                _context.Maquina.Remove(maquina);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MaquinaExists(int id)
        {
            return (_context.Maquina?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

OcupacaoMaquinaOFC/Views/Maquinas/Create.cshtml
@model OcupacaoMaquinaOFC.Models.Maquina

@{
    ViewData["Title"] = "Adicionar máquina";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Adicionar uma nova máquina</h1>

<h4>Maquina</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" placeholder="Ex: Mufla" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LimiteHoras" class="control-label"></label>
                <input type="number" step="0.1" placeholder="Ex: 24" asp-for="LimiteHoras" class="form-control" />
                <span asp-validation-for="LimiteHoras" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValorMaquina" class="control-label"></label>
                <input type="number" step="0.01" placeholder="Ex: 200000.00" asp-for="ValorMaquina" class="form-control" />
                <span asp-validation-for="ValorMaquina" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar máquina" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

OcupacaoMaquinaOFC/Views/Maquinas/Delete.cshtml
@model OcupacaoMaquinaOFC.Models.Maquina

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Deletar</h1>

<h3>Você tem certeza que deseja deletar esta máquina?</h3>
<div>
    <h4>Máquina</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd><dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LimiteHoras)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LimiteHoras)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValorMaquina)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValorMaquina)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValorHora)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValorHora)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Nome" />
        <input type="submit" value="Excluir máquina" class="btn btn-danger" /> 
        <a asp-action="Index">Voltar</a>
    </form>
</div>

OcupacaoMaquinaOFC/Views/Maquinas/Details.cshtml
@model OcupacaoMaquinaOFC.Models.Maquina

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Detalhes</h1>

<div>
    <h4>--> @Model.Nome</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd><dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LimiteHoras)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LimiteHoras)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValorMaquina)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValorMaquina)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ValorHora)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ValorHora)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Editar</a> |
    <a asp-action="Index">Voltar</a>
</div>

OcupacaoMaquinaOFC/Views/Maquinas/Edit.cshtml
@model OcupacaoMaquinaOFC.Models.Maquina

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Editar</h1>

<h4>Maquina</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" placeholder="Ex: Mufla" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LimiteHoras" class="control-label"></label>
                <input type="number" step="0.1" placeholder="Ex: 24" asp-for="LimiteHoras" class="form-control" />
                <span asp-validation-for="LimiteHoras" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValorMaquina" class="control-label"></label>
                <input type="number" step="0.01" placeholder="Ex: 200000.00" asp-for="ValorMaquina" class="form-control" />
                <span asp-validation-for="ValorMaquina" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

OcupacaoMaquinaOFC/Views/Maquinas/Index.cshtml
@model IEnumerable<OcupacaoMaquinaOFC.Models.Maquina>

@{
    ViewData["Title"] = "Máquinas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Máquinas</h1>

<p>
    <a asp-action="Create">Adicionar nova máquina</a>
</p>

<form asp-controller="Maquinas" asp-action="Index" method="get">
    <p>
        <input type="text" placeholder="Buscar máquinas..." name="SearchString" />
        <input type="submit" value="Buscar"/>
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LimiteHoras)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ValorMaquina)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ValorHora)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LimiteHoras)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ValorMaquina)
            </td><td>
                @Html.DisplayFor(modelItem => item.ValorHora)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Exibir detalhes</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Deletar</a>
            </td>
        </tr>
}
    </tbody>
</table>